/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/west2-online/fzuhelper-server/api/model/api"
	"github.com/west2-online/fzuhelper-server/api/mw"
	"github.com/west2-online/fzuhelper-server/api/pack"
	"github.com/west2-online/fzuhelper-server/api/rpc"
	"github.com/west2-online/fzuhelper-server/kitex_gen/course"
	"github.com/west2-online/fzuhelper-server/kitex_gen/model"
	metainfoContext "github.com/west2-online/fzuhelper-server/pkg/base/context"
	"github.com/west2-online/fzuhelper-server/pkg/constants"
	"github.com/west2-online/fzuhelper-server/pkg/errno"
	"github.com/west2-online/fzuhelper-server/pkg/utils"
)

// GetCourseList .
// @router /api/v1/jwch/course/list [GET]
func GetCourseList(ctx context.Context, c *app.RequestContext) {
	var req api.CourseListRequest
	var err error

	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	res, err := rpc.GetCourseListRPC(ctx, &course.CourseListRequest{
		Term:      req.Term,
		IsRefresh: req.IsRefresh,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.CourseListResponse)
	resp.Data = pack.BuildCourseList(res)
	pack.RespList(c, resp.Data)
}

// GetTermList .
// @router /api/v1/jwch/term/list [GET]
func GetTermList(ctx context.Context, c *app.RequestContext) {
	res, err := rpc.GetCourseTermsListRPC(ctx, &course.TermListRequest{})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.CourseTermListResponse)
	resp.Data = res.Data
	pack.RespList(c, resp.Data)
}

// GetLocateDate .
// @router /api/v1/course/date [GET]
func GetLocateDate(ctx context.Context, c *app.RequestContext) {
	resp := new(api.GetLocateDateResponse)
	date, err := rpc.GetLocateDateRPC(ctx, &course.GetLocateDateRequest{})
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.LocateDate = pack.BuildLocateDate(date)
	pack.RespData(c, resp.LocateDate)
}

// SubscribeCalendar .
// @router /api/v1/course/calendar/subscribe [GET]
func SubscribeCalendar(ctx context.Context, c *app.RequestContext) {
	var err error
	// 从 ctx 中获取解析后的 stu_id
	stuId, ok := c.Get(constants.StuIDContextKey)
	if !ok {
		pack.RespError(c, errno.ParamError)
		return
	}
	res, err := rpc.GetCalendarRPC(ctx, &course.GetCalendarRequest{
		StuId: stuId.(string),
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}
	c.Data(consts.StatusOK, "text/calendar", res)
}

// GetCalendar .
// @router /api/v1/jwch/course/calendar/token [GET]
func GetCalendar(ctx context.Context, c *app.RequestContext) {
	// 生成 calendar token
	var token string
	loginData, err := metainfoContext.GetLoginData(ctx)
	if err != nil {
		pack.RespError(c, errno.AuthError.WithError(err))
		return
	}
	// 签发 calendar token，并包含学号
	token, err = mw.CreateToken(constants.TypeCalendarToken, utils.RemoveUndergraduatePrefix(loginData.Id))
	if err != nil {
		pack.RespError(c, errno.AuthError.WithError(err))
		return
	}
	pack.RespData(c, token)
}

// GetFriendCourse .
// @router /api/v1/course/friend [GET]
func GetFriendCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFriendCourseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}
	res, err := rpc.GetFriendCourseRPC(ctx, &course.GetFriendCourseRequest{
		Id:   req.GetStudentID(),
		Term: req.Term,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp := new(api.GetFriendCourseResponse)

	resp.Data = pack.BuildCourseList(res)
	pack.RespList(c, resp.Data)
}

// GetAutoAdjustCourseList .
// @router /api/v1/course/adjust/list [GET]
func GetAutoAdjustCourseList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetAutoAdjustCourseListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	res, err := rpc.GetAutoAdjustCourseListRPC(ctx, &course.GetAutoAdjustCourseListRequest{
		Term: req.Term,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.GetAutoAdjustCourseListResponse)
	resp.Data = pack.BuildAdjustCourseList(res)
	pack.RespList(c, resp.Data)
}

// UpdateAdjustCourse .
// @router /api/v1/course/adjust/ [PUT]
func UpdateAdjustCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateAdjustCourseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	err = rpc.UpdateAutoAdjustCourseRPC(ctx, &course.UpdateAdjustCourseRequest{
		Id:       req.ID,
		Secret:   req.Secret,
		Enabled:  req.Enabled,
		FromDate: req.FromDate,
		ToDate:   req.ToDate,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// UploadCustomCourse .
// @router /api/v1/jwch/course/custom/upload [POST]
func UploadCustomCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadCustomCourseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	var courses []*model.SyncCustomCourseRequestData
	for _, courseData := range req.Courses {
		var scheduleRules []*model.CourseScheduleRule
		for _, rule := range courseData.ScheduleRules {
			scheduleRules = append(scheduleRules, &model.CourseScheduleRule{
				Location:   rule.Location,
				StartClass: rule.StartClass,
				EndClass:   rule.EndClass,
				StartWeek:  rule.StartWeek,
				EndWeek:    rule.EndWeek,
				Weekday:    rule.Weekday,
				Single:     rule.Single,
				Double:     rule.Double,
				Adjust:     rule.Adjust,
			})
		}
		courses = append(courses, &model.SyncCustomCourseRequestData{
			Id:             courseData.ID,
			Name:           courseData.Name,
			Teacher:        courseData.Teacher,
			Location:       courseData.Location,
			Color:          courseData.Color,
			Note:           courseData.Note,
			ScheduleRules:  scheduleRules,
			LastUpdateTime: courseData.LastUpdateTime,
		})
	}

	serverVersion, err := rpc.UploadCustomCourseRPC(ctx, &course.UploadCustomCourseRequest{
		Semester: req.Semester,
		Courses:  courses,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.UploadCustomCourseResponse)
	resp.Base = pack.BuildBaseResp(nil)
	resp.ServerVersion = serverVersion
	c.JSON(consts.StatusOK, resp)
}

// GetCustomCourseList .
// @router /api/v1/jwch/course/custom/list [GET]
func GetCustomCourseList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetCustomCourseListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	res, err := rpc.GetCustomCourseListRPC(ctx, &course.GetCustomCourseListRequest{
		Semester: req.Semester,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.GetCustomCourseListResponse)
	resp.Base = pack.BuildBaseResp(nil)
	resp.ServerVersion = res.ServerVersion
	resp.Data = pack.BuildCustomCourseList(res.Data)
	c.JSON(consts.StatusOK, resp)
}

// SyncCustomCourse .
// @router /api/v1/jwch/course/custom/sync [POST]
func SyncCustomCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SyncCustomCourseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	var addedCourses []*model.SyncCustomCourseRequestData
	if req.AddedCourses != nil {
		for _, courseData := range req.AddedCourses {
			var scheduleRules []*model.CourseScheduleRule
			for _, rule := range courseData.ScheduleRules {
				scheduleRules = append(scheduleRules, &model.CourseScheduleRule{
					Location:   rule.Location,
					StartClass: rule.StartClass,
					EndClass:   rule.EndClass,
					StartWeek:  rule.StartWeek,
					EndWeek:    rule.EndWeek,
					Weekday:    rule.Weekday,
					Single:     rule.Single,
					Double:     rule.Double,
					Adjust:     rule.Adjust,
				})
			}
			addedCourses = append(addedCourses, &model.SyncCustomCourseRequestData{
				Id:             courseData.ID,
				Name:           courseData.Name,
				Teacher:        courseData.Teacher,
				Location:       courseData.Location,
				Color:          courseData.Color,
				Note:           courseData.Note,
				ScheduleRules:  scheduleRules,
				LastUpdateTime: courseData.LastUpdateTime,
			})
		}
	}

	var updatedCourses []*model.SyncCustomCourseRequestData
	if req.UpdatedCourses != nil {
		for _, courseData := range req.UpdatedCourses {
			var scheduleRules []*model.CourseScheduleRule
			for _, rule := range courseData.ScheduleRules {
				scheduleRules = append(scheduleRules, &model.CourseScheduleRule{
					Location:   rule.Location,
					StartClass: rule.StartClass,
					EndClass:   rule.EndClass,
					StartWeek:  rule.StartWeek,
					EndWeek:    rule.EndWeek,
					Weekday:    rule.Weekday,
					Single:     rule.Single,
					Double:     rule.Double,
					Adjust:     rule.Adjust,
				})
			}
			updatedCourses = append(updatedCourses, &model.SyncCustomCourseRequestData{
				Id:             courseData.ID,
				Name:           courseData.Name,
				Teacher:        courseData.Teacher,
				Location:       courseData.Location,
				Color:          courseData.Color,
				Note:           courseData.Note,
				ScheduleRules:  scheduleRules,
				LastUpdateTime: courseData.LastUpdateTime,
			})
		}
	}

	res, err := rpc.SyncCustomCourseRPC(ctx, &course.SyncCustomCourseRequest{
		Semester:         req.Semester,
		ClientVersion:    req.ClientVersion,
		AddedCourses:     addedCourses,
		UpdatedCourses:   updatedCourses,
		DeletedCourseIds: req.DeletedCourseIds,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.SyncCustomCourseResponse)
	resp.Base = pack.BuildBaseResp(nil)
	resp.ServerVersion = res.ServerVersion
	resp.NewCourses = pack.BuildSyncCustomCourseResponseDataList(res.NewCourses_)
	resp.UpdatedCourses = pack.BuildSyncCustomCourseResponseDataList(res.UpdatedCourses)
	resp.DeletedCourseIds = res.DeletedCourseIds
	c.JSON(consts.StatusOK, resp)
}

// DeleteCustomCourse .
// @router /api/v1/jwch/course/custom/delete [POST]
func DeleteCustomCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteCustomCourseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	err = rpc.DeleteCustomCourseRPC(ctx, &course.DeleteCustomCourseRequest{
		Semester:  req.Semester,
		CourseIds: req.CourseIds,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}
